### ISSUE TITLE
Look forward to answering a few questions

### ISSUE THREAD

**Issue by SisMaker** [arangodb/velocystream#1]
I am implementing the client side of this protocol, but I have some questions. One reply of a messageId request may have multiple chunks and then one request may have multiple replies. How can I assemble the chunks and the replies and return them to the requester?

**Comment by SisMaker** [comment]
if the driver use the pool , and one request hase multiple reply, the requester need to multiple get the reply?

**Comment by neunhoef** [comment]
As far as I know the spec should be clear about how to assemble chunks to a reply. They are basically just concatenated, using the number of the chunk to sort them. I think we guarantee that the chunks of a message are transmitted in ascending chunk number. That is easy and well specified.

The fact that a single request can have multiple responses is a future extension possibility, and is currently not used anywhere in the API. In principle, one could implement a stream of messages with this, all answering to a single request. But as I said, this is currently not used. I would probably not implement this for now in a client. Maybe even put an assertion in that there is only one response to a request.

**Comment by SisMaker** [comment]
Thank you very much. It would be much easier if  didn't care about multiple replies.I know how to do it. Thank you again
