### ISSUE TITLE
about velocy pack object sort

### ISSUE THREAD

**Issue by SisMaker** [arangodb/velocystream#2]
the velocy pack document show 
"Objects are always stored with sorted key/value pairs, sorted by bytewise comparions of the keys on each nesting level. Sorting has some overhead but will allow looking up keys in logarithmic time later. Note that only the index table needs to be sorted, it is not required that the offsets in these tables are increasing. Since the index table resides after the actual subvalues, one can build up a complex VPack value by writing linearly."  
I have a question whether the object that Velocystream transmits such as the parameter, meta, body must to be sort key and then code?

**Comment by jsteemann** [comment]
In general, an object (e.g. `{ "foo": "bar", "b": 2, "a": 1 }`) can be stored in VelocyPack in a sorted or unsorted way. In the unsorted way, the attributes in the object have no particular order in storage and when iterating over them. For VelocyPack sorted objects, the object attributes are stored in memory in an arbitrary order, but the object contains an index table at the end, in which there are offsets to the attributes in the object. These offsets are sorted in a way so that iterating over the index table linearly yields the object attributes in sorted order.
For the above object, for example, it could look as follows:
```
0x0b 0x14 0x03 0x43 0x66 0x6f 0x6f 0x43 0x62 0x61 0x72 0x41 0x62 0x32 0x41 0x61 
0x31 0x0e 0x0b 0x03
```
Breakdown of this object (offset, value, meaning):
```
header:
0x00  0x0b = sorted object, offsets and number of attributes are stored as 8 bit values
0x01  0x14 = total length of data (including header)
0x02  0x03 = number of attributes (3)
data:
0x03  0x43 = string of length 3
0x04  0x66, 0x6f, 0x6f = "foo"
0x07  0x43 = string of length 3
0x08  0x62, 0x61, 072 = "bar"
0x0b  0x41 = string of length 1
0x0c  0x62 = "b"
0x0d  0x32 = integer value 2
0x0e  0x41 = string of length 1
0x0f  0x61 = "a"
0x10  0x31 = integer value 1
index table:
0x11  0x0e = attribute #1 begins at offset 0x0e
0x12  0x0b = attribute #2 begins at offset 0x0b
0x13  0x03 = attribute #3 begins at offset 0x03
```
The above is an example for a sorted object with index table.
There also exist unsorted objects, which lack the index tables.

Both sorted objects (0x0b - 0x0e) and unsorted objects (0x14, 0x0a) are valid VelocyPack encodings. You can use whatever you prefer.

VelocyStream as well is not restricted to using sorted objects. Objects in VelocyStream can be either sorted or unsorted, as long as they are encoded correctly.

**Comment by SisMaker** [comment]
I asked the question because in my tests I found that if meta and Parameter objects were not coded in the sort key, Velocystream would return 400 from the request and would return correctly only if they were coded in the sort key way

**Comment by SisMaker** [comment]
If meta and Parameter can encode in the way of unsort key in the Velocystream request, and I get 400 back in my test, it may be that I made a mistake in my Velocy pack serialization library encode unsort Key Object

**Comment by jsteemann** [comment]
It really should not matter if the objects are sorted or not. It is just a matter of efficiency.
If you want to validate the velocypack that you built, you can do by building the tools from https://github.com/arangodb/velocypack/blob/main/tools/vpack-validate.cpp and checking your binary data against it.

**Comment by SisMaker** [comment]
ok, thank you！ i will check the velocy pack encode unsort key objest is right, thanks.

**Comment by SisMaker** [comment]
first i have a question, Sort whether object key is ASC or DESC?

and other problem i encode the object ({ "foo": "bar", "b": 2, "a": 1 }) whit sort key  get the binary data whith index table 
"
0b // sorted object, offsets and number of attributes are stored as 8 bit values
14 // total length of data (including header)
03 // total length of data (including header)
41 61 31  // string of key length 1 and key value {"a": 1}
41 62 32  // string of key length 1 and key value {"b": 2}
43 66 6f 6f  43 62 61 72  //  the key value {"foo": "bar"} 
09 06 03  // index table
" 
this can be check pass by vpack-validate(https://github.com/arangodb/velocypack/blob/main/tools/vpack-validate.cpp)
but if i encode  the object ({ "foo": "bar", "b": 2, "a": 1 }) whit unsort key get the binary data whith index table 
"
0f // unsorted object, offsets and number of attributes are stored as 8 bit values
14 // total length of data (including header)
03 // total length of data (including header)
41 61 31  // string of key length 1 and key value {a: 1}
41 62 32  // string of key length 1 and key value {b: 2}
43 66 6f 6f  43 62 61 72  //  the key value {"foo": "bar"} 
09 06 03  // index table
"
this can not  be check pass by vpack-validate
the sort and unsort key encode the ({ "foo": "bar", "b": 2, "a": 1 }) object get bianry only diff different  in the type value of "ob" "of"
but the second can not be check pass by the vpack-validate, 
I am confused.
looking forward to your reply !!!
thank you.

**Comment by jsteemann** [comment]
> first i have a question, Sort whether object key is ASC or DESC?

It is always ascending.

**Comment by jsteemann** [comment]
Re unsorted objects:
if you don't want to use sorted objects, you can always use a "compact" object (type 0x14).
This type of object does not have any index table at all, so it will be smaller than an object with an index table.

Here is an example:
**Sorted object with index table**:
```
$ echo '{ "foo": "bar", "b": 2, "a": 1 }' | build/tools/json-to-vpack --no-compact --hex
0x0b 0x14 0x03 0x43 0x66 0x6f 0x6f 0x43 0x62 0x61 0x72 0x41 0x62 0x32 0x41 0x61 
0x31 0x0e 0x0b 0x03
```
**Unsorted, compact object (no index table)**:
```
$ echo '{ "foo": "bar", "b": 2, "a": 1 }' | build/tools/json-to-vpack --compact --hex
0x14 0x11 0x43 0x66 0x6f 0x6f 0x43 0x62 0x61 0x72 0x41 0x62 0x32 0x41 0x61 0x31 
0x03
```
As you can see, the 3 index table entries at the end are now missing, plus the length is smaller by 3 bytes. This is the way to go if you don't require sortedness.

Iterating over a sorted object in sorted order then requires iterating over the values in the index table, and fetching the values at each offset.
Iterating over a sorted object in non-deterministic (i.e. build oder) is also possible by starting the iteration directly behind the length/number of items data, and then simply scanning until you have read all attributes and values.

The same applies for an unsorted compact object: start the iteration directly behind the length/number of items data, and then scan until you have read all attributes and values. 
However, iteration in sorted order is not possible on unsorted compact objects.

**Comment by SisMaker** [comment]
> > 首先我有一个问题，排序对象键是ASC还是DESC？
> 
> 它总是在上升。

It looks like your example
 $ echo '{ "foo": "bar", "b": 2, "a": 1 }' | build/tools/json-to-vpack --no-compact --hex
0x0b 0x14 0x03 0x43 0x66 0x6f 0x6f 0x43 0x62 0x61 0x72 0x41 0x62 0x32 0x41 0x61 
0x31 0x0e 0x0b 0x03     is DESC

**Comment by SisMaker** [comment]
> Re unsorted objects:
> if you don't want to use sorted objects, you can always use a "compact" object (type 0x14).
> This type of object does not have any index table at all, so it will be smaller than an object with an index table.
> 
> Here is an example:
> **Sorted object with index table**:
> 
> ```
> $ echo '{ "foo": "bar", "b": 2, "a": 1 }' | build/tools/json-to-vpack --no-compact --hex
> 0x0b 0x14 0x03 0x43 0x66 0x6f 0x6f 0x43 0x62 0x61 0x72 0x41 0x62 0x32 0x41 0x61 
> 0x31 0x0e 0x0b 0x03
> ```
> 
> **Unsorted, compact object (no index table)**:
> 
> ```
> $ echo '{ "foo": "bar", "b": 2, "a": 1 }' | build/tools/json-to-vpack --compact --hex
> 0x14 0x11 0x43 0x66 0x6f 0x6f 0x43 0x62 0x61 0x72 0x41 0x62 0x32 0x41 0x61 0x31 
> 0x03
> ```
> 
> As you can see, the 3 index table entries at the end are now missing, plus the length is smaller by 3 bytes. This is the way to go if you don't require sortedness.
> 
> Iterating over a sorted object in sorted order then requires iterating over the values in the index table, and fetching the values at each offset.
> Iterating over a sorted object in non-deterministic (i.e. build oder) is also possible by starting the iteration directly behind the length/number of items data, and then simply scanning until you have read all attributes and values.
> 
> The same applies for an unsorted compact object: start the iteration directly behind the length/number of items data, and then scan until you have read all attributes and values.
> However, iteration in sorted order is not possible on unsorted compact objects.

For object encode, I implemented unsort and Compact, unsort and no compact, sort and no compact, which was an option for API interface, but it seemed that unsort and no Compact could not work properly in velocy Stream Request and could not be checked by Vpack-validate

**Comment by jsteemann** [comment]
Sorry, I can't follow quite.

It looks like both the sorted and the compact variants validate properly with the `vpack-validate` executable:
```
$ echo '{ "foo": "bar", "b": 2, "a": 1 }' | build/tools/json-to-vpack --no-compact | build/tools/vpack-validate 
The velocypack in infile '/proc/self/fd/0' is valid

$ echo '{ "foo": "bar", "b": 2, "a": 1 }' | build/tools/json-to-vpack --compact | build/tools/vpack-validate 
The velocypack in infile '/proc/self/fd/0' is valid
```

I didn't try the non-compact, unsorted object types, as there is no way to generate them using `json-to-vpack`. I also think we dropped support for them in ArangoDB as there was no great value of having unsorted objects when there are also compact objects.

In case a specific object does not validate, please paste the exact byte sequence here (in hex) so I can check.

**Comment by jsteemann** [comment]
> It looks like your example
> $ echo '{ "foo": "bar", "b": 2, "a": 1 }' | build/tools/json-to-vpack --no-compact --hex
> 0x0b 0x14 0x03 0x43 0x66 0x6f 0x6f 0x43 0x62 0x61 0x72 0x41 0x62 0x32 0x41 0x61 
> 0x31 0x0e 0x0b 0x03     is DESC 

No, the _build_ order is descending here (though it can be arbitrary), but the _index_ table order is ascending. It is only the index table that is sorted.

The motivation for this is to allow building object attributes in arbitrary order by programs to save moving large areas of memory around for sorting, but still allow efficient/sorted access to the individual attributes in them.

So you can write programs such as
```
Builder b;
b.openObject();
b.add("foo", Value("bar"));
b.add("b", Value(2));
b.add("a", Value(1));
b.close();
```
that add attributes in arbitrary order to the object. The call to "close()" here will add the sorted index table _behind_ the already added data, which for large objects will be much more efficient than sorting all the already added attributes and their values in memory. Plus it allows getting away without having a temporary swap buffer that would be need to sort the object attributes and values in place.

**Comment by SisMaker** [comment]
> > It looks like your example
> > $ echo '{ "foo": "bar", "b": 2, "a": 1 }' | build/tools/json-to-vpack --no-compact --hex
> > 0x0b 0x14 0x03 0x43 0x66 0x6f 0x6f 0x43 0x62 0x61 0x72 0x41 0x62 0x32 0x41 0x61
> > 0x31 0x0e 0x0b 0x03     is DESC
> 
> No, the _build_ order is descending here (though it can be arbitrary), but the _index_ table order is ascending. It is only the index table that is sorted.
> 
> The motivation for this is to allow building object attributes in arbitrary order by programs to save moving large areas of memory around for sorting, but still allow efficient/sorted access to the individual attributes in them.
> 
> So you can write programs such as
> 
> ```
> Builder b;
> b.openObject();
> b.add("foo", Value("bar"));
> b.add("b", Value(2));
> b.add("a", Value(1));
> b.close();
> ```
> 
> that add attributes in arbitrary order to the object. The call to "close()" here will add the sorted index table _behind_ the already added data, which for large objects will be much more efficient than sorting all the already added attributes and their values in memory. Plus it allows getting away without having a temporary swap buffer that would be need to sort the object attributes and values in place.

"
0b // sorted object, offsets and number of attributes are stored as 8 bit values
14 // total length of data (including header)
03 // total length of data (including header)
41 61 31 // string of key length 1 and key value {"a": 1}
41 62 32 // string of key length 1 and key value {"b": 2}
43 66 6f 6f 43 62 61 72 // the key value {"foo": "bar"}
09 06 03 // index table
"
this can be check pass by vpack-validate(https://github.com/arangodb/velocypack/blob/main/tools/vpack-validate.cpp)
but if i encode the object ({ "foo": "bar", "b": 2, "a": 1 }) whit unsort key get the binary data whith index table
"
0f // unsorted object, offsets and number of attributes are stored as 8 bit values
14 // total length of data (including header)
03 // total length of data (including header)
41 61 31 // string of key length 1 and key value {a: 1}
41 62 32 // string of key length 1 and key value {b: 2}
43 66 6f 6f 43 62 61 72 // the key value {"foo": "bar"}
09 06 03 // index table
"
We assume that the order of unsort keys is the same when encode an object as when sort key. In this way, the contents produced by sort key and unsort key encode are the same, just like the top side, only the Velocy pack type is different. One is oxOB and the other is oxOF, but the second vpack-validate does not pass.

**Comment by SisMaker** [comment]
Thank you for all your answers, I'm going to discard the unsorted key encoding object API.
